#!/bin/bash

RPM_OUTPUT=$(sensors | grep "${BLOCK_INSTANCE:-Fan}")
CURRENT_RPM=$(echo "${RPM_OUTPUT}" | grep -o -E "[\+\-]?[0-9]*.[0-9]*RPM" | sed -n '1p')

echo "${CURRENT_RPM}"
echo "${CURRENT_RPM}"
echo ""
